using System.Collections.Generic;
using System.IO;
using System.Text;
using Sirenix.OdinInspector;
using Somnambulo.Scripts.Runtime.Core.Models.Ids;
using UnityEngine;
#if UNITY_EDITOR
using UnityEditor;
#endif

namespace Somnambulo.Scripts.Runtime.Core.Models.Databases
{
    [CreateAssetMenu(fileName = "TriggerIdsDatabase", menuName = "Somnambulo/Databases/TriggerIdsDatabase")]
    public class TriggerIdsDatabase : ScriptableObject
    {
        // ================== DATA ==================
        
        [Title("Storage")]
        [InfoBox("Auto-filled by the 'Scan & Generate' button below.", InfoMessageType.None)]
        [ReadOnly] [SerializeField] private List<TriggerId> content = new();

        private Dictionary<string, TriggerId> map;

        // ================== RUNTIME LOGIC ==================

        public void Initialize()
        {
            if (map != null) return;

            map = new Dictionary<string, TriggerId>(content.Count);
            foreach (var item in content)
            {
                if (item == null) continue;
                map.TryAdd(item.StringId, item);
            }
            Debug.Log($"[TriggerDatabase] Initialized {map.Count} IDs.");
        }

        public TriggerId Get(string id)
        {
            if (map == null) Initialize();
            return map.GetValueOrDefault(id);
        }

        // ================== GENERATION (EDITOR ONLY) ==================
#if UNITY_EDITOR
        [Title("Actions")]
        [Button(ButtonSizes.Large), GUIColor(0.6f, 1f, 0.6f)]
        private void ScanAndGenerate()
        {
            // 1. SCAN
            content.Clear();
            string[] guids = AssetDatabase.FindAssets("t:TriggerId");
            
            foreach (var guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                var trigger = AssetDatabase.LoadAssetAtPath<TriggerId>(path);
                content.Add(trigger);
            }
            
            EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();

            // 2. GENERATE
            GenerateClassFile();
        }

        private void GenerateClassFile()
        {
            var relativePath = "/_Project/Scripts/Runtime/Core/Generated"; 
            var folderPath = Application.dataPath + relativePath;
            var filePath = folderPath + "/Triggers.cs";

            if (!Directory.Exists(folderPath)) Directory.CreateDirectory(folderPath);

            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine("// <auto-generated> This file is generated by TriggerIdsDatabase. Do not modify. </auto-generated>");
            stringBuilder.AppendLine("using Somnambulo.Scripts.Runtime.Core.Models.Databases;");
            stringBuilder.AppendLine("using Somnambulo.Scripts.Runtime.Core.Models.Ids;");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("namespace Somnambulo.Scripts.Runtime.Core.Generated");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine("    public class Triggers");
            stringBuilder.AppendLine("    {");
            stringBuilder.AppendLine("        private readonly TriggerIdsDatabase database;");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("        public Triggers(TriggerIdsDatabase database)");
            stringBuilder.AppendLine("        {");
            stringBuilder.AppendLine("            this.database = database;");
            stringBuilder.AppendLine("            this.database.Initialize();");
            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine();

            foreach (var item in content)
            {
                if (item == null) continue;
                
                // Getting rid of spaces and minuses for C#
                var validName = item.name.Replace(" ", "_").Replace("-", "_");
                
                // Generating property
                stringBuilder.AppendLine($"        public TriggerId {validName} => database.Get(\"{item.name}\");");
            }

            stringBuilder.AppendLine("    }");
            stringBuilder.AppendLine("}");

            File.WriteAllText(filePath, stringBuilder.ToString());
            AssetDatabase.Refresh();
            
            Debug.Log($"[TriggerIdsDatabase] Generated 'Triggers.cs' at {relativePath}");
        }
#endif
    }
}