// <auto-generated> This file is generated by TriggerIdsDatabase. Do not modify. </auto-generated>
using Somnambulo.Scripts.Runtime.Core.Models.Databases;
using Somnambulo.Scripts.Runtime.Core.Models.Ids;

namespace Somnambulo.Scripts.Runtime.Core.Generated
{
    public class Triggers
    {
        private readonly TriggerIdsDatabase database;

        public Triggers(TriggerIdsDatabase database)
        {
            this.database = database;
            this.database.Initialize();
        }

        public TriggerId test_trigger_1 => database.Get("test_trigger_1");
        public TriggerId test_trigger_2 => database.Get("test_trigger_2");
        public TriggerId test_trigger_3 => database.Get("test_trigger_3");
        public TriggerId test_trigger_4 => database.Get("test_trigger_4");
    }
}
